#!/bin/bash

docker run -dit --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/develop/go:/home/user/go -v $HOME/.atom-docker:/home/user/.atom --name=atom guoguojin/ubuntu-go-atom:1.18.0
